//
// RestResponseListOrdersDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RestResponseListOrdersDTO: Codable, JSONEncodable, Hashable {

    /** 响应状态码 */
    public var code: Int
    /** 响应消息 */
    public var message: String
    public var data: RestResponseOrders

    public init(code: Int, message: String, data: RestResponseOrders) {
        self.code = code
        self.message = message
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encode(data, forKey: .data)
    }
}

