//
// RestResponseOrders.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RestResponseOrders: Codable, JSONEncodable, Hashable {

    /** 订单列表 */
    public var items: [OrderDTO]?
    public var page: RestResponsePage?

    public init(items: [OrderDTO]? = nil, page: RestResponsePage? = nil) {
        self.items = items
        self.page = page
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case page
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(page, forKey: .page)
    }
}

