//
// TemperatureOption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** 饮品温度选项 (对应 Swift 枚举): - 0: 冰饮 (iced) - 1: 热饮 (hot) - 2: 常温 (warm)  */
public enum TemperatureOption: Int, Codable, CaseIterable {
    case ICED = 0
    case HOT = 1
    case WARM = 2
}
